<?php

namespace Database\Seeders;

use App\Models\sales\ResponseCode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CodeResponsePaymentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $code_error = [


            ['code' => '100','description'  => 'Transacción Exitosa',                                                                                                                                                                  'message' => 'Transacción exitosa',                                                                                              'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '101','description'  => 'Transacción rechazada, faltan uno o dos campos en la solicitud',                                                                                                                       'message' => 'Transacción exitosa',                                                                                              'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '102','description'  => 'Datos no validos',                                                                                                                                                                     'message' => 'Datos de tarjeta incorrectos',                                                                                     'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '104','description'  => 'Se detectó una transacción duplicada. Es posible que la transacción ya se haya procesado.',                                                                                         'message' => 'Posible transacción duplicada.',                                                                                   'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '110','description'  => 'Solo se aprobó una cantidad parcial.',                                                                                                                                                 'message' => 'Se aprobó una cantidad parcial.',                                                                                  'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '150','description'  => 'Falla general del sistema.',                                                                                                                                                           'message' => 'Falla de VisaNet. Intentar más tarde.',                                                                            'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '151','description'  => 'Se recibió la solicitud pero se produjo un tiempo de espera del servidor.',                                                                                                            'message' => 'Tiempo de espera excedido.',                                                                                       'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '152','description'  => 'Se recibió la solicitud pero se produjo un tiempo de espera del servicio.',                                                                                                            'message' => 'Tiempo de espera excedido.',                                                                                       'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '200','description'  => 'La solicitud fue aprobado por el banco emisor pero rechazada por CyberSource.',                                                                                                        'message' => 'Reversión automática.',                                                                                            'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '201','description'  => 'El banco emisor tiene preguntas sobre la solicitud. No recibe un código de autorización mediante programación, pero puede recibir uno verbalmente llamando al procesador.',         'message' => 'Banco emisor solicita confirmación.',                                                                              'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '202','description'  => 'Tarjeta expirada o fecha ingresada incorrecta.',                                                                                                                                       'message' => 'Tarjeta expirada o fecha de expiración incorrecta.',                                                               'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '203','description'  => 'Rechazo general de la tarjeta. El banco emisor no proporcionó ninguna otra información.',                                                                                           'message' => 'Rechazo de la tarjeta.',                                                                                           'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '204','description'  => 'Fondos insuficientes.',                                                                                                                                                                'message' => 'Fondos insuficientes.',                                                                                            'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '205','description'  => 'Tarjeta robada o perdida',                                                                                                                                                             'message' => 'Tarjeta robada o perdida.',                                                                                        'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '207','description'  => 'Banco emisor no disponible',                                                                                                                                                           'message' => 'Banco emisor no disponible.',                                                                                      'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '208','description'  => 'Tarjeta inactiva o sin autorización para transacciones en línea',                                                                                                                      'message' => 'Tarjeta inactiva o sin autorización para transacciones en línea',                                                  'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '210','description'  => 'La tarjeta ha alcanzado el límite de crédito.',                                                                                                                                        'message' => 'Límite de crédito alcanzado ',                                                                                     'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '211','description'  => 'CVV invalido.',                                                                                                                                                                        'message' => 'CVV invalido.',                                                                                                    'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '221','description'  => 'El cliente hizo coincidir una entrada en el archivo negativo del procesador.',                                                                                                         'message' => 'Transacción en listado negativo.',                                                                                 'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '222','description'  => 'Cuenta Congelada',                                                                                                                                                                     'message' => 'Cuenta Congelada',                                                                                                 'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '230','description'  => 'La solicitud de autorización fue aprobada por el banco emisor, pero CyberSource la rechazó porque no pasó el cheque CVV.',                                                             'message' => 'Reversión automática.',                                                                                            'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '231','description'  => 'Número de cuenta inválido',                                                                                                                                                            'message' => 'Número de cuenta inválido',                                                                                        'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '232','description'  => 'Tipo de tarjeta inválida.',                                                                                                                                                            'message' => 'Tipo de tarjeta no compatible.',                                                                                   'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '233','description'  => 'Declinación general por parte del procesador.',                                                                                                                                        'message' => 'Tarjeta no aceptada por VisaNet',                                                                                  'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '234','description'  => 'Problema con la información en la cuenta de CyberSource.',                                                                                                                             'message' => 'Error de validador.',                                                                                              'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '236','description'  => 'Falla del procesador.',                                                                                                                                                                'message' => 'Falla del procesador.',                                                                                            'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '240','description'  => 'El tipo de tarjeta enviado no es válido o no se correlaciona con el número de la tarjeta de pago.',                                                                                    'message' => 'El tipo de tarjeta es invalido o no corresponde al número de la tarjeta.',                                         'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '475','description'  => 'El titular de la tarjeta está inscrito para la autenticación del pagador.',                                                                                                            'message' => 'Se requiere autenticación del titular.',                                                                           'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '476','description'  => 'No se pudo autenticar al pagador.',                                                                                                                                                    'message' => 'No se pudo autenticar al pagador.',                                                                                'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '481','description'  => 'La transacción se rechazó en función de la configuración de pago para el perfil.',                                                                                                     'message' => 'Alto nivel de riesgo de parte de la tarjeta.',                                                                     'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '520','description'  => 'La solicitud de autorización fue aprobada por el banco emisor, pero CyberSource la rechazó en función de su configuración de Autorización inteligente heredada.',                      'message' => 'Reversión automática.',                                                                                            'language' => 'ES',           'code_payment' => 'CYBERSOURCE'],


            ['code' => '100','description'  => 'Successful Transaction',                                                                                                                                                               'message' => 'Successful transaction',                                                                                           'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '101','description'  => 'Transaction rejected, one or two fields are missing in the application',                                                                                                               'message' => 'Successful transaction',                                                                                           'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '102','description'  => 'Invalid data',                                                                                                                                                                         'message' => 'Incorrect card data',                                                                                              'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '104','description'  => 'A duplicate transaction was detected. The transaction may have already been processed.',                                                                                            'message' => 'Possible duplicate transaction.',                                                                                  'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '110','description'  => 'Only a partial amount was approved.',                                                                                                                                                  'message' => 'A partial amount was approved.',                                                                                   'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '150','description'  => 'General system failure.',                                                                                                                                                              'message' => 'VisaNet failure. Please try again later.',                                                                         'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '151','description'  => 'The request was received but there was a server timeout.',                                                                                                                             'message' => 'Waiting time exceeded.',                                                                                           'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '152','description'  => 'The application was received but there was a service wait time.',                                                                                                                      'message' => 'Waiting time exceeded.',                                                                                           'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '200','description'  => 'The application was approved by the issuing bank but rejected by CyberSource.',                                                                                                        'message' => 'Automatic reversion.',                                                                                             'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '201','description'  => 'The issuing bank has questions about the application. It does not receive an authorization code programmatically, but can receive one verbally by calling the processor.',          'message' => 'Issuing bank requests confirmation.',                                                                              'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '202','description'  => 'Card expired or incorrect date entered.',                                                                                                                                              'message' => 'Expired card or incorrect expiration date.',                                                                       'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '203','description'  => 'General rejection of the card. No other information was provided by the issuing bank.',                                                                                             'message' => 'Rejection of the card.',                                                                                           'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '204','description'  => 'Insufficient funds.',                                                                                                                                                                  'message' => 'Insufficient funds.',                                                                                              'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '205','description'  => 'Lost or stolen card',                                                                                                                                                                  'message' => 'Stolen or lost card.',                                                                                             'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '207','description'  => 'Issuing bank not available',                                                                                                                                                           'message' => 'Issuing bank not available.',                                                                                      'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '208','description'  => 'Inactive or unauthorized card for online transactions',                                                                                                                                'message' => 'Inactive or unauthorized card for online transactions',                                                            'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '210','description'  => 'The card has reached the credit limit.',                                                                                                                                               'message' => 'Credit limit reached ',                                                                                            'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '211','description'  => 'CVV invalid.',                                                                                                                                                                         'message' => 'CVV invalid.',                                                                                                     'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '221','description'  => 'The customer matched an entry in the processors negative file.',                                                                                                                       'message' => 'Negative listing transaction.',                                                                                    'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '222','description'  => 'Frozen Account',                                                                                                                                                                       'message' => 'Frozen Account',                                                                                                   'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '230','description'  => 'The authorization request was approved by the issuing bank, but CyberSource rejected it because it did not pass the CVV check.',                                                       'message' => 'Automatic reversion.',                                                                                             'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '231','description'  => 'Invalid account number',                                                                                                                                                               'message' => 'Invalid account number',                                                                                           'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '232','description'  => 'Invalid card type.',                                                                                                                                                                   'message' => 'Card type not supported.',                                                                                         'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '233','description'  => 'General decline on the part of the processor.',                                                                                                                                        'message' => 'Card not accepted by VisaNet',                                                                                     'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '234','description'  => 'Problem with CyberSource account information.',                                                                                                                                        'message' => 'Validator error.',                                                                                                 'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '236','description'  => 'Processor failure.',                                                                                                                                                                   'message' => 'Processor failure.',                                                                                               'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '240','description'  => 'The card type sent is invalid or does not correlate with the payment card number.',                                                                                                    'message' => 'The card type is invalid or does not correspond to the card number.',                                              'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '475','description'  => 'The cardholder is enrolled for payer authentication.',                                                                                                                                 'message' => 'Authentication of the holder is required.',                                                                        'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '476','description'  => 'The payer could not be authenticated.',                                                                                                                                                'message' => 'The payer could not be authenticated.',                                                                            'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '481','description'  => 'The transaction was declined based on the payment settings for the profile.',                                                                                                          'message' => 'High level of risk on the part of the card.',                                                                      'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],
            ['code' => '520','description'  => 'The authorization request was approved by the issuing bank, but CyberSource rejected it based on its legacy Smart Authorization settings.',                                            'message' => 'Automatic reversion.',                                                                                             'language' => 'INGL',           'code_payment' => 'CYBERSOURCE'],


        ];

        foreach ($code_error as $value) {

            ResponseCode::updateOrCreate(
                [
                    'code'          => $value['code'],
                    'language'      => $value['language'],
                    'code_payment'  => $value['code_payment'],
                ],
                [
                    'description'   => $value['description'],
                    'message'       => $value['message'],
                ]
            );
        }
    }
}
